"use strict";
const Miu={canvas:null,ctx:null,sprite:new Image(),sound:true,active:null,keys:{},raf:0,session:0,
high(g){const n=Number.parseInt(localStorage.getItem(`miu_highscore_${g}`),10);return Number.isFinite(n)&&n>0?n:0;},save(g,s){s=Number.isFinite(s)?Math.floor(s):0;if(s>this.high(g))localStorage.setItem(`miu_highscore_${g}`,String(s));this.updateScores();},updateScores(){["adventure","runner","catchfish","skyjump"].forEach(g=>{const e=document.querySelector(`#score-${g}`);if(e)e.textContent=`REKOR: ${this.high(g)}`;});},audioContext(){return this.audio||(this.audio=new(window.AudioContext||window.webkitAudioContext)());},tone(t){if(!this.sound)return;const a=this.audioContext(),o=a.createOscillator(),g=a.createGain(),f={jump:440,fish:760,hit:150,over:100,win:660,button:520}[t]||400;o.frequency.value=f;o.type=t==="hit"?"sawtooth":"square";g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.13);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.14);},jingle(){if(!this.sound)return;const a=this.audioContext();[0,.18,.36,.6].forEach((t,i)=>{const o=a.createOscillator(),g=a.createGain();o.type="triangle";o.frequency.value=[523,659,784,1046][i];g.gain.setValueAtTime(.04,a.currentTime+t);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+t+.2);o.connect(g).connect(a.destination);o.start(a.currentTime+t);o.stop(a.currentTime+t+.22);});},rect(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;},
resetContext(c){c.globalAlpha=1;c.filter="none";c.globalCompositeOperation="source-over";},drawMiu(c,x,y,w,h,flip=false,bob=0){c.save();this.resetContext(c);c.translate(x+w/2,y+h/2+bob);if(flip)c.scale(-1,1);if(this.sprite.ready)c.drawImage(this.sprite,-w/2,-h/2,w,h);else{c.fillStyle="#f58a36";c.fillRect(-w/2,-h/2,w,h);c.fillStyle="#283044";c.fillRect(-w*.2,-h*.2,5,5);c.fillRect(w*.2-5,-h*.2,5,5);}c.restore();},hud(c,lines){c.save();this.resetContext(c);c.fillStyle="#283044d9";c.fillRect(12,12,Math.min(430,lines.length*130),34);c.fillStyle="#fff";c.font="bold 14px monospace";lines.forEach((s,i)=>c.fillText(s,22+i*130,34));c.restore();},
hideOverlay(){const o=document.querySelector("#game-overlay");o.hidden=true;o.className="overlay";o.style.cssText="";o.replaceChildren();},showOverlay(title,detail,actions){this.hideOverlay();const o=document.querySelector("#game-overlay");o.classList.add("visible");o.innerHTML=`<h2>${title}</h2><p>${detail}</p><div>${actions.map(a=>`<button data-action="${a.id}">${a.label}</button>`).join("")}</div>`;o.hidden=false;actions.forEach(a=>o.querySelector(`[data-action="${a.id}"]`).onclick=a.run);},
stop(){this.session++;cancelAnimationFrame(this.raf);this.raf=0;this.active=null;},finish(state,title,detail){const g=this.active;if(!g||g.state!=="PLAYING")return;g.state=state;this.save(this.lastGame,g.currentScore());this.tone(state==="VICTORY"?"win":"over");this.showOverlay(title,detail,[{id:"retry",label:"COBA LAGI",run:()=>startGame(this.lastGame)},{id:"menu",label:"MENU UTAMA",run:showMenu}]);},pause(){const g=this.active;if(!g)return;if(g.state==="PLAYING"){g.state="PAUSED";this.showOverlay("GAME DIJEDA","Posisi dan skor Miu tersimpan di sesi ini.",[{id:"resume",label:"LANJUTKAN",run:()=>this.pause()},{id:"retry",label:"ULANGI",run:()=>startGame(this.lastGame)},{id:"menu",label:"MENU UTAMA",run:showMenu}]);}else if(g.state==="PAUSED"){this.hideOverlay();g.state="PLAYING";}}
};
Miu.sprite.onload=()=>Miu.sprite.ready=true;Miu.sprite.onerror=()=>console.warn("Sprite Miu belum ditemukan di assets/miu.png");Miu.sprite.src="assets/miu.png";
function startGame(name){Miu.stop();Miu.hideOverlay();Miu.lastGame=name;document.body.classList.add("game-playing");localStorage.setItem(`miu_played_${name}`,"true");document.querySelector("#menu-screen").classList.remove("active");document.querySelector("#game-screen").classList.add("active");document.querySelector("#game-title").textContent={adventure:"Miu Adventure",runner:"Miu Endless Run",catchfish:"Miu Catch Fish",skyjump:"Miu Sky Jump"}[name];Miu.canvas=document.querySelector("#game-canvas");Miu.ctx=Miu.canvas.getContext("2d");Miu.ctx.imageSmoothingEnabled=false;Miu.active=MiuGames[name]();configureTouchControls(name);document.querySelector("#game-hint").textContent=Miu.active.hint+(isTouchLike()?" · Kontrol sentuh aktif di bawah permainan.":"");Miu.tone("button");const token=++Miu.session;let last=performance.now();const loop=now=>{if(token!==Miu.session||!Miu.active)return;const dt=Math.min(.033,Math.max(0,(now-last)/1000));last=now;if(Miu.active.state==="PLAYING")Miu.active.update(dt);Miu.resetContext(Miu.ctx);Miu.active.render(Miu.ctx);Miu.raf=requestAnimationFrame(loop);};Miu.raf=requestAnimationFrame(loop);}
function showMenu(){Miu.hideOverlay();Miu.stop();document.body.classList.remove("game-playing");clearVirtualKeys();document.querySelector("#game-screen").classList.remove("active");document.querySelector("#menu-screen").classList.add("active");Miu.updateScores();}
function isTouchLike(){return (navigator.maxTouchPoints||0)>0||matchMedia("(pointer: coarse)").matches;}
function clearVirtualKeys(){["arrowleft","arrowright"," ","shift"].forEach(k=>Miu.keys[k]=false);document.querySelectorAll(".touch-key.pressed").forEach(b=>b.classList.remove("pressed"));}
function bindHoldButton(id,key){const b=document.querySelector(id);if(!b)return;const press=e=>{e.preventDefault();Miu.keys[key]=true;b.classList.add("pressed");try{b.setPointerCapture(e.pointerId);}catch(_){}};const release=e=>{if(e)e.preventDefault();Miu.keys[key]=false;b.classList.remove("pressed");};b.addEventListener("pointerdown",press);b.addEventListener("pointerup",release);b.addEventListener("pointercancel",release);b.addEventListener("lostpointercapture",release);b.addEventListener("contextmenu",e=>e.preventDefault());}
function configureTouchControls(name){const controls=document.querySelector("#touch-controls"),direction=document.querySelector("#touch-direction"),run=document.querySelector("#touch-run"),jump=document.querySelector("#touch-jump");if(!controls)return;clearVirtualKeys();controls.dataset.game=name;direction.hidden=name==="runner";run.hidden=name!=="adventure";jump.hidden=!(name==="adventure"||name==="runner");}
function pulseJump(){if(!Miu.active||Miu.active.state!=="PLAYING")return;Miu.keys[" "]=true;setTimeout(()=>{Miu.keys[" "]=false;document.querySelector("#touch-jump")?.classList.remove("pressed");},130);}
document.addEventListener("DOMContentLoaded",()=>{Miu.sound=localStorage.getItem("miu-sound")!=="off";const sound=document.querySelector("#sound-button"),sync=()=>sound.textContent=`♫ SUARA: ${Miu.sound?"ON":"OFF"}`;sync();Miu.updateScores();document.querySelector("#start-adventure").onclick=()=>{Miu.jingle();document.querySelector("#intro-screen").hidden=true;showMenu();};document.querySelectorAll("[data-game]").forEach(b=>b.onclick=()=>startGame(b.dataset.game));document.querySelector("#menu-button").onclick=showMenu;document.querySelector("#logo").onclick=e=>{e.preventDefault();showMenu();};document.querySelector("#pause-button").onclick=()=>Miu.pause();sound.onclick=()=>{Miu.sound=!Miu.sound;localStorage.setItem("miu-sound",Miu.sound?"on":"off");sync();};document.querySelector("#reset-button").onclick=()=>{if(confirm("Hapus semua rekor Miu?")){["adventure","runner","catchfish","skyjump"].forEach(g=>localStorage.removeItem(`miu_highscore_${g}`));Miu.updateScores();}};const d=document.querySelector("#help-dialog");document.querySelector("#help-button").onclick=()=>d.showModal();d.querySelector(".close-dialog").onclick=()=>d.close();
  bindHoldButton("#touch-left","arrowleft");bindHoldButton("#touch-right","arrowright");bindHoldButton("#touch-run","shift");
  const jump=document.querySelector("#touch-jump");jump.addEventListener("pointerdown",e=>{e.preventDefault();jump.classList.add("pressed");pulseJump();});jump.addEventListener("pointerup",e=>{e.preventDefault();Miu.keys[" "]=false;jump.classList.remove("pressed");});jump.addEventListener("pointercancel",()=>{Miu.keys[" "]=false;jump.classList.remove("pressed");});jump.addEventListener("contextmenu",e=>e.preventDefault());
  const canvas=document.querySelector("#game-canvas");canvas.addEventListener("pointerdown",e=>{if(Miu.lastGame==="runner"&&Miu.active?.state==="PLAYING"&&e.pointerType!=="mouse"){e.preventDefault();pulseJump();}});
  addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowUp"," "].includes(e.key))e.preventDefault();Miu.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==="p")Miu.pause();});addEventListener("keyup",e=>Miu.keys[e.key.toLowerCase()]=false);addEventListener("blur",clearVirtualKeys);document.addEventListener("visibilitychange",()=>{if(document.hidden)clearVirtualKeys();});});
